Repository developmentseed/ml-enabler, pull requests merged in 2020-08, with the labels that each got.

#65 Model Search
  ml_enabler/api/ml.py
  ml_enabler/models/ml_model.py
  ml_enabler/services/ml_model_service.py
  web/src/components/Home.vue
Labels: enhancement

#67 Validation UI Bug
  web/src/components/Home.vue
  web/src/components/prediction/Map.vue
Labels: bug

#70 Working pager component
  ml_enabler/api/ml.py
  ml_enabler/models/ml_model.py
  ml_enabler/services/ml_model_service.py
  web/src/App.vue
  web/src/components/Home.vue
  web/src/components/util/Pager.vue
Labels: enhancement

#71 Dependency Update
  requirements.txt
  web/yarn.lock
Labels: enhancement

#76 Fix click listener
  web/src/components/prediction/Map.vue
Labels: bug

#75 Integrations
  migrations/versions/69f682394874_.py
  ml_enabler/__init__.py
  ml_enabler/api/imagery.py
  ml_enabler/api/integration.py
  ml_enabler/api/ml.py
  ml_enabler/api/task.py
  ml_enabler/models/dtos/ml_model_dto.py
  ml_enabler/models/imagery.py
  ml_enabler/models/integration.py
  ml_enabler/models/ml_model.py
  ml_enabler/models/utils.py
  ml_enabler/services/imagery_service.py
  ml_enabler/services/integration_service.py
  web/src/components/Imagery.vue
  web/src/components/Integration.vue
  web/src/components/Model.vue
Labels: enhancement

#77 Npz Export Fix
  ml_enabler/api/ml.py
Labels: bug

#78 Dep Up 2
  task-build/package.json
  task-build/yarn.lock
  task-retrain/requirements.txt
Labels: dependencies

#80 No Task Message
  web/src/components/prediction/Tasks.vue
Labels: enhancement

#79 Prompt
  cloudformation/ml-enabler.template.js
  ml_enabler/config.py
Labels: enhancement

#81 Duplicate Semver
  migrations/versions/138ccd6ff566_.py
  ml_enabler/api/ml.py
  ml_enabler/models/ml_model.py
  ml_enabler/models/prediction.py
  ml_enabler/models/utils.py
  ml_enabler/services/prediction_service.py
Labels: enhancement

#83 la croix color theme for mapped preds
  web/src/components/prediction/Map.vue
Labels: enhancement

#84 Mr. Integration
  migrations/versions/7abacee99e4d_.py
  ml_enabler/api/integration.py
  ml_enabler/api/ml.py
  ml_enabler/models/integration.py
  ml_enabler/models/ml_model.py
  ml_enabler/models/prediction.py
  ml_enabler/services/integration_service.py
  ml_enabler/services/prediction_service.py
  requirements.txt
  web/src/components/Integrations.vue
  web/src/components/Model.vue
  web/src/components/Prediction.vue
  web/src/components/prediction/Assets.vue
  web/src/components/prediction/Export.vue
  web/src/components/prediction/Map.vue
  web/src/main.js
Labels: enhancement

#85 Non Geospatial
  migrations/versions/1e7eb18a9fe8_.py
  ml_enabler/models/dtos/ml_model_dto.py
  ml_enabler/models/imagery.py
  web/src/components/Imagery.vue
  web/src/components/Model.vue
  web/src/components/prediction/Stack.vue
Labels: enhancement

#88 Log
  ml_enabler/api/ml.py
Labels: enhancement

#86 Generic Img
  cloudformation/prediction.template.json
  lambda/download_and_predict/base.py
  lambda/download_and_predict/handler.py
  ml_enabler/api/ml.py
  web/src/components/prediction/Stack.vue
Labels: enhancement
